// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdgonensumpfeurkqfvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkZ29uZW5zdW1wZmV1cmtxZnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTgwNTksImV4cCI6MjA2NzI3NDA1OX0.s_54sR4DJj6of5Po7bzQZEtXMfl0rP0MdiQ-60miVS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});